#!/bin/sh

dir_bin=/home/cmb/tmatsumu/LB_SYSPL/LB_SYSPL_v4.4/pyScans/

# LiteBIRD sidelobe source 

# (option of shell input)
# (title)
# (sampleing [Hz])
# (sec in a day)
# (precession angle [degs])
# (precession period [min])
# (spin axis angle [degs])
# (spin axis period [rpm])
# (sim run period [days])
# (nside for projection)

# this script was used to compare with the pointing generated by the Guillaume and also the Tomo's pyScan pointing running on the local laptop in python.

date=20180116_example2

python ${dir_bin}/src/run_scan_todgen_c.mod.py y LB_L2_${date}_samplerate 0.1 1500. 65. 93. 30. 0.1 1 16
